name: C/C++ CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build_ubuntu-amd64_latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prerequisites
    # pre-installed on ubuntu-1804: build-essential, git 2.28.0, cmake 3.10/3.17, make
    # pre-installed: clang 6.0 / 8 / 9, gcc/++ 7.5.0/8.4.0/9.3.0
      run: sudo apt -qq update && sudo apt -yqq install libusb-1.0-0-dev
    - name: cmake_make
      run: mkdir build && cmake -S . -B build && cd build && make
    - name: compress
      run: tar zcvf librtlsdr_build_ubuntu-amd64_latest.tar.gz --directory=build/src --exclude=CMakeFiles --exclude=*.cmake --exclude=Makefile --exclude=rtl_app_ver.h .
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu_latest_build
        path: librtlsdr_build_ubuntu-amd64_latest.tar.gz

  build_macos_latest:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    #- name: prerequisites
    # pre-installed on macos-10.15: git 2.28.0, cmake 3.18.2, libusb 1.0.23
    # pre-installed: clang/LLVM 10.0.1, gcc/++ 8.4.0/9.3.0
    #  run: brew install libusb
    - name: cmake_make
      run: mkdir build && cmake -S . -B build && cd build && make
    - name: compress
      run: tar zcvf librtlsdr_build_macos-latest.tar.gz --directory=build/src --exclude=CMakeFiles --exclude=*.cmake --exclude=Makefile --exclude=rtl_app_ver.h .
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: macos_latest_build
        path: librtlsdr_build_macos-latest.tar.gz

  cross_build_win32_win64_latest:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: prerequisites
      run: sudo apt -qq update && sudo apt -yqq install gcc-mingw-w64
    - name: build_w32_static
      run: bash ./cross_build_mingw32.sh static -DLINK_RTLTOOLS_AGAINST_STATIC_LIB=ON
    - name: build_w32_static_udpsrv
      run: bash ./cross_build_mingw32.sh static_udpsrv -DLINK_RTLTOOLS_AGAINST_STATIC_LIB=ON -DPROVIDE_UDP_SERVER=ON
    - name: build_w32_dlldep
      run: bash ./cross_build_mingw32.sh dlldep
    - name: build_w32_dlldep_udpsrv
      run: bash ./cross_build_mingw32.sh dlldep_udpsrv -DPROVIDE_UDP_SERVER=ON

    - name: build_w64_static
      run: bash ./cross_build_mingw64.sh static -DLINK_RTLTOOLS_AGAINST_STATIC_LIB=ON
    - name: build_w64_static_udpsrv
      run: bash ./cross_build_mingw64.sh static_udpsrv -DLINK_RTLTOOLS_AGAINST_STATIC_LIB=ON -DPROVIDE_UDP_SERVER=ON
    - name: build_w64_dlldep
      run: bash ./cross_build_mingw64.sh dlldep
    - name: build_w64_dlldep_udpsrv
      run: bash ./cross_build_mingw64.sh dlldep_udpsrv -DPROVIDE_UDP_SERVER=ON

    - name: 'upload w32 static artifact'
      uses: actions/upload-artifact@v2
      with:
        name: rtlsdr-bin-w32_static
        path: rtlsdr-bin-w32_static/bin/
    - name: 'upload w32 static_udpsrv artifact'
      uses: actions/upload-artifact@v2
      with:
        name: rtlsdr-bin-w32_static_udpsrv
        path: rtlsdr-bin-w32_static_udpsrv/bin/
    - name: 'upload w32 dlldep artifact'
      uses: actions/upload-artifact@v2
      with:
        name: rtlsdr-bin-w32_dlldep
        path: rtlsdr-bin-w32_dlldep/bin/
    - name: 'upload w32 dlldep_udpsrv artifact'
      uses: actions/upload-artifact@v2
      with:
        name: rtlsdr-bin-w32_dlldep_udpsrv
        path: rtlsdr-bin-w32_dlldep_udpsrv/bin/

    - name: 'upload w64 static artifact'
      uses: actions/upload-artifact@v2
      with:
        name: rtlsdr-bin-w64_static
        path: rtlsdr-bin-w64_static/bin/
    - name: 'upload w64 static_udpsrv artifact'
      uses: actions/upload-artifact@v2
      with:
        name: rtlsdr-bin-w64_static_udpsrv
        path: rtlsdr-bin-w64_static_udpsrv/bin/
    - name: 'upload w64 dlldep artifact'
      uses: actions/upload-artifact@v2
      with:
        name: rtlsdr-bin-w64_dlldep
        path: rtlsdr-bin-w64_dlldep/bin/
    - name: 'upload w64 dlldep_udpsrv artifact'
      uses: actions/upload-artifact@v2
      with:
        name: rtlsdr-bin-w64_dlldep_udpsrv
        path: rtlsdr-bin-w64_dlldep_udpsrv/bin/

